config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  # resources :users
  resources :comments
  resources :users do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Validations
  validates :body, presence: true
  # Associations
  belongs_to :user, counter_cache: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Validations
  validates :username,:email, presence: true , uniqueness: true
  
  # Associations
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: %i[index]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:first_name,:last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: %i[edit update destroy]

    # GET /users/:user_id/comments
    def index
        @user=User.find_by(id:params[:user_id])
        @comments=@user.comments

    end

    #POST /comments
    def create
        @users=User.all
        @comment_new=Comment.new(comment_params)
        @comment_new.user=current_user
        respond_to do |format|
            if @comment_new.save
                format.html { redirect_to root_path, notice: "Comment was successfully created." }
            else
                format.html { render "users/index", status: :unprocessable_entity }
            end
        end
    
    end
    # GET /comments/:id/edit
    def edit; end

    # PATCH	/comments/:id
    def update
        respond_to do |format|
            if @comment.update(comment_params)
                format.html { redirect_to user_comments_path(@comment.user), notice: "Comment was successfully updated." }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end

    end
    # DELETE /comments/:id
    def destroy

        @comment.destroy
        redirect_to user_comments_path(@comment.user)

    end

    private
    def set_comment
        @comment = Comment.find_by(id: params[:id])
    end
    def comment_params
        params.require(:comment).permit(:body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users=User.all
        @comment_new=Comment.new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<div>
<%= form_with  model:@comment do |form| %>
        <div class="form-comment-container">
            <div>
                <div class="form-comment">
                <%= form.text_field :body ,placeholder: "Remember to thing before write..." %>
                <% if @comment.errors.messages[:body].any? %>
                    <span class="content--sm input__error-message">
                        <%= @comment.errors.messages[:body].join(", ")%>
                    </span>
                <% end %>
                </div>
                <div class="comment-button">
                    <%= form.submit "Update" %>
                </div>
                <%= link_to "back",user_comments_path(@comment.user),class: "back"%>
            </div>
        </div>      
<% end %>

</div>

app/views/comments/index.html.erb
<div class="comments_by_user">
    <div>
        <p>User: @<%=@user.username %></p>
    </div>
    <div>Comments:</div>
    <div style="width:600px">
    <% @comments.each do |comment| %>
        <div class="comments-options">
            <p>- <%= comment.body %></p>
            <div class="options-icons">
                <% if current_user && current_user.comments.include?(comment)%>
                    <div>
                        <%= link_to image_tag("/images/icons/edit.svg") , edit_comment_path(comment)  %>
                    </div>
                    <div>
                        <%= button_to comment_path(comment), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>
                            <%= image_tag("/images/icons/trash.svg") %>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    <% end %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <div class="navbar">
        <% if user_signed_in? %>
            <div class="create-session">
              <%= button_to destroy_user_session_path, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>
                  <%= 'Logout' %>
              <% end %>
            </div>
        <% else %>
          <div class="create-session">
            <div><%= link_to 'Login', new_user_session_path, class: "session-tweet" %></div>
            <div><%= link_to 'SignUp', new_user_registration_path, class: "session-tweet" %></div>
          </div>
        <% end %>
      </div>
      <%= link_to root_path do %>
        <div class="title-home">Home</div>
      <% end %>
     
      <div class="flash-alerts">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="users-list">
    <div>
    <% if current_user %>
        <%= form_with  model:@comment_new do |form| %>
                <div class="form-comment-container">
                    <div>
                        <div class="form-comment">
                        <%= form.text_field :body ,placeholder: "Remember to thing before write..." %>
                        <% if @comment_new.errors.messages[:body].any? %>
                            <span class="content--sm input__error-message">
                                <%= @comment_new.errors.messages[:body].join(", ")%>
                            </span>
                        <% end %>
                        </div>
                        <div class="comment-button">
                            <%= form.submit "Comment" %>
                        </div>
                    </div>
                </div>      
        <% end %>
    <% end %>
    </div>
    <hr/>
    <div class="user-container">
        <% @users.each do |user| %>
            <div class="user-comment">
                <div>- @<%= user.username %> has
                <span>
                <% if user.comments_count==1 %>
                    <%= user.comments_count %><span> comment</span>
                <% else %>
                    <%= user.comments_count || 0 %><span> comments</span>
                <% end %>
                </div>
                <%= link_to image_tag("/images/icons/comment-icon.svg") ,user_comments_path(user) %>
            </div>
        <% end %>

    </div>

</div>